### ISSUE TITLE
路径最好是有意义一点

### ISSUE THREAD

**Issue by afc163** [ant-design/u.ant.design#1]
类似

- https://fb.me/react-unknown-prop
- https://fb.me/invalid-aria-props

**Comment by afc163** [comment]
```
$ npm run generate https://www.alipay.com alipay
https://www.alipay.com ==shorten=> http://u.ant.design/alipay
```

**Comment by benjycui** [comment]
https://github.com/ant-design/u.ant.design/blob/gh-pages/url.map.js 这个文件是可以直接编辑的。。

**Comment by benjycui** [comment]
自动生成有意义的路径，感觉不现实。
